### ISSUE TITLE
[Server] Check Initial Configuration Values

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cm-honeybee#21]
- Readme에 설명된 설정과, 메인스트림 소스에 포함된 설정 파일의 기본 설정이 다릅니다. 
- 가급적 초기 설정 값으로 동일하게 제공하는 것이 사용자에게 이해하기 쉬울 것 같습니다. 
- 저에 경우 Readme 설정 값으로 수정 후 시험하였습니다. 

<br>

[Agent]
- https://github.com/cloud-barista/cm-honeybee/blob/main/agent/conf/cm-honeybee-agent.yaml
  ```
  cm-honeybee-agent:
      listen:
          port: 8082
  ```

[Server]
- https://github.com/cloud-barista/cm-honeybee/blob/main/server/conf/cm-honeybee.yaml
  ```
  cm-honeybee:
      listen:
          port: 8081
      agent:
          port: 8082
  ```
